import JSZip from 'jszip'
import type { ArcadeConfig } from './arcadeConfig'

export async function createArcadeBundle(
  arcadeConfig: ArcadeConfig,
  demoModel: Blob,
  modelName: string,
  modelPath: string,
): Promise<Blob> {
  const archive = new JSZip()

  archive.file(modelName, demoModel)
  archive.file('arcade-config.json', JSON.stringify(arcadeConfig, null, 2))
  archive.file(
    'README.txt',
    `PolyPacker hackathon demo asset bundle\n\n${modelName} is a pre-made demo model selected locally to match the prompt (${modelPath}); it was not generated by an API.\narcade-config.json contains the config generated by Gemini.`,
  )

  return archive.generateAsync({ type: 'blob' })
}
