import JSZip from 'jszip'
import type { ArcadeConfig } from './arcadeConfig'

export type BundleModel =
  | { blob: Blob; filename: string; source: 'Hyper3D' }
  | { blob: Blob; filename: string; source: 'demo'; path: string }

export async function createArcadeBundle(
  arcadeConfig: ArcadeConfig,
  model: BundleModel,
): Promise<Blob> {
  const archive = new JSZip()

  archive.file(model.filename, model.blob)
  archive.file('arcade-config.json', JSON.stringify(arcadeConfig, null, 2))
  archive.file(
    'README.txt',
    model.source === 'Hyper3D'
      ? `PolyPacker asset bundle\n\n${model.filename} was generated with Hyper3D.\narcade-config.json contains the config generated by Gemini.`
      : `PolyPacker hackathon demo asset bundle\n\n${model.filename} is a pre-made demo model selected locally to match the prompt (${model.path}); it was not generated by an API.\narcade-config.json contains the config generated by Gemini.`,
  )

  return archive.generateAsync({ type: 'blob' })
}
